services:
  postgres:
    image: postgres:17-alpine
    container_name: unyowo-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: unyowo
      POSTGRES_PASSWORD: unyowo
      POSTGRES_DB: unyowo
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: unyowo-redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  mailpit:
    image: axllent/mailpit:latest
    container_name: unyowo-mailpit
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  pgdata:
